Repository Lazarus-org/dj-system-monitor, pull requests merged in 2025-02, with the labels that each got.

#1 feat: Add .gitignore file
  .gitignore
Labels: enhancement

#2 feat: Add base app structure
  dj_system_monitor/__init__.py
  dj_system_monitor/admin.py
  dj_system_monitor/apps.py
  dj_system_monitor/migrations/__init__.py
  dj_system_monitor/models.py
  dj_system_monitor/views.py
Labels: enhancement

#3 feat(models): Add base models
  dj_system_monitor/models.py
Labels: enhancement

#4 feat(admin): Add base admins
  dj_system_monitor/admin.py
Labels: enhancement

#5 Develop
  dj_system_monitor/management/__init__.py
  dj_system_monitor/management/commands/__init__.py
  dj_system_monitor/management/commands/collect_metrics.py
  dj_system_monitor/serializers.py
  dj_system_monitor/templates/dashboard.html
  dj_system_monitor/urls.py
  dj_system_monitor/views.py
Labels: enhancement

#19 Chore/pyproject
  .gitignore
  packages/requirements-dev.txt
  packages/requirements.txt
  poetry.lock
  pyproject.toml
  tox.ini
Labels: enhancement

#24 Refactor/style
  dj_system_monitor/admin.py
  dj_system_monitor/management/__init__.py
  dj_system_monitor/management/commands/__init__.py
  dj_system_monitor/management/commands/collect_metrics.py
  dj_system_monitor/migrations/__init__.py
  dj_system_monitor/models.py
  dj_system_monitor/serializers.py
  dj_system_monitor/templates/dashboard.html
  dj_system_monitor/urls.py
  dj_system_monitor/views.py
  system_monitor/__init__.py
  system_monitor/apps.py
  system_monitor/models.py
  system_monitor/urls.py
Labels: enhancement

#25 :hammer: refactor(admin): Add ModelAdmin dynamic site config & new fi…
  system_monitor/admin.py
Labels: enhancement

#30 Feat/settings
  system_monitor/constants/__init__.py
  system_monitor/constants/default_settings.py
  system_monitor/constants/types.py
  system_monitor/settings/__init__.py
  system_monitor/settings/checks.py
  system_monitor/settings/conf.py
  system_monitor/validators/__init__.py
  system_monitor/validators/config_validators.py
Labels: enhancement

#32 feat: Add SystemMetricsCalculator class for resource usage calculation
  system_monitor/calculator.py
Labels: enhancement

#33 Refactor/api
  system_monitor/api/__init__.py
  system_monitor/api/paginations/__init__.py
  system_monitor/api/paginations/limit_offset_pagination.py
  system_monitor/api/serializers/__init__.py
  system_monitor/api/serializers/resource_usage.py
  system_monitor/api/throttlings/__init__.py
  system_monitor/api/throttlings/role_base_throttle.py
  system_monitor/api/views/__init__.py
  system_monitor/api/views/resource_usage.py
  system_monitor/mixins/__init__.py
  system_monitor/mixins/api/__init__.py
  system_monitor/mixins/api/config_api_attrs.py
  system_monitor/mixins/api/control_api_methods.py
Labels: enhancement

#35 :hammer: refactor(views): Add dynamic pemission check logic based on …
  system_monitor/templates/dashboard.html
  system_monitor/views.py
Labels: enhancement

#37 Tests
  system_monitor/tests/__init__.py
  system_monitor/tests/admin/__init__.py
  system_monitor/tests/admin/test_resource_usage.py
  system_monitor/tests/api/__init__.py
  system_monitor/tests/api/paginations/__init__.py
  system_monitor/tests/api/paginations/test_limit_offset_pagination.py
  system_monitor/tests/api/throttlings/__init__.py
  system_monitor/tests/api/throttlings/test_role_base_throttle.py
  system_monitor/tests/api/views/__init__.py
  system_monitor/tests/api/views/test_resource_usage.py
  system_monitor/tests/commands/__init__.py
  system_monitor/tests/commands/test_collect_metrics.py
  system_monitor/tests/conftest.py
  system_monitor/tests/constants.py
  system_monitor/tests/fixtures/__init__.py
  system_monitor/tests/fixtures/admin.py
  system_monitor/tests/fixtures/models.py
  system_monitor/tests/fixtures/user.py
  system_monitor/tests/fixtures/views.py
  system_monitor/tests/models/__init__.py
  system_monitor/tests/models/test_resource_usage.py
  system_monitor/tests/settings/__init__.py
  system_monitor/tests/settings/test_checks.py
  system_monitor/tests/settings/test_conf.py
  system_monitor/tests/setup.py
  system_monitor/tests/urls.py
  system_monitor/tests/validators/__init__.py
  system_monitor/tests/validators/test_config_validators.py
  system_monitor/tests/views/__init__.py
  system_monitor/tests/views/test_dashboard.py
Labels: test

#38 style: Add migration file & improve code style
  system_monitor/api/serializers/resource_usage.py
  system_monitor/api/views/resource_usage.py
  system_monitor/calculator.py
  system_monitor/constants/default_settings.py
  system_monitor/management/commands/collect_metrics.py
  system_monitor/migrations/0001_initial.py
  system_monitor/migrations/0002_alter_resourceusage_options_and_more.py
  system_monitor/migrations/__init__.py
  system_monitor/models.py
  system_monitor/settings/checks.py
  system_monitor/views.py
Labels: enhancement

#39 :green_heart: ci: Add CI for testing & automate deploy
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: enhancement

#45 refactor(commands): Update timezone usage to make it compatible with …
  README.md
  system_monitor/calculator.py
  system_monitor/management/commands/collect_metrics.py
Labels: enhancement

#47 :bug: fix(poetry): package not found error on build
  poetry.lock
  pyproject.toml
  tox.ini
Labels: bug

#49 :books: docs(README): Add complete documentation as mark down file
  README.md
Labels: documentation

#52 :zap: update(migrations) remove redundant migration files
  system_monitor/migrations/0001_initial.py
  system_monitor/migrations/0002_alter_resourceusage_options_and_more.py
Labels: bug
